version: '2'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  userdb:
    image: postgres:9.5.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jetlinks_user_db