server:
  port: 9012
logging:
  level:
    business: TRACE
spring:
  aop:
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    max-active: 1000
    initial-size: 5
    min-idle: 5
    max-wait: 50000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    validation-query: select 1
    time-between-eviction-runs-millis: 60000
    max-open-prepared-statements: 2000
  application:
    name: @artifactId@
  profiles:
    active: dev
  cloud:
    stream:
      default:
        group: ${spring.application.name}
        consumer:
          header-mode: raw
          content-type: application/json
        producer:
          header-mode: raw
          content-type: application/json
hsweb:
  app:
    name: 设备网关服务
    version: 1.0.0
feign:
  hystrix:
    enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 2000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 1
jetlinks:
  redis:
    clients:
      default:  #默认client
        hosts: redis://127.0.0.1:6379
        database: 0
      device-registry:  #设备注册中心,使用redis数据库2
        hosts: redis://127.0.0.1:6379
        database: 1
vertx:
  prefer-native-transport: true # linux下使用epoll,macos下使用kqueue
  mqtt:
    port: 1883
    accept-backlog: 2048
    send-buffer-size: 10240
    receive-buffer-size: 65536
    max-message-size: 65536
    ssl: false #是否开启ssl
    pfx-key-cert-options: # p12 双向认证
      path: ./ssl/jetlinks_server.p12
      password: jetlinks
  max-event-loop-execute-time: 20
  max-worker-execute-time-unit: seconds
  max-worker-execute-time: 20
  max-event-loop-execute-time-unit: seconds

gateway:
  server-id: ${spring.application.name}:${server.port}