version: '2'
services:
  nacos:    # nacos 配置中心以及服务发现
    image: nacos/nacos-server:1.0.0
    container_name: jetlinks-all-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./nacos.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
  redis:
    image: redis:5.0.4
    container_name: jetlinks-all-redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    command: redis-server --appendonly yes
  postgres:
    image: postgres:9.5.6-alpine
    container_name: jetlinks-all-postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: jetlinks
      POSTGRES_DB: jetlinks
      TZ: Asia/Shanghai
  elasticsearch:
    image: elasticsearch:5.6.11
    container_name: jetlinks-all-elasticsearch
    environment:
      ES_JAVA_OPTS: -Djava.net.preferIPv4Stack=true -Xms1g -Xmx1g
      transport.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      discovery.zen.ping.unicast.hosts: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:5.6.11
    container_name: jetlinks-all-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  influxdb:
    image: influxdb:1.7
    container_name: jetlinks-all-influxdb
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: jetlinks
      INFLUXDB_ADMIN_USER: jetlinks
      INFLUXDB_ADMIN_PASSWORD: jetlinks
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      TZ: Asia/Shanghai
    ports:
      - "8086:8086"
      - "8083:8083"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: jetlinks-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: jetlinks
      RABBITMQ_DEFAULT_USER: jetlinks
      RABBITMQ_DEFAULT_PASS: jetlinks
      TZ: Asia/Shanghai
    ports:
      - "15672:15672"
      - "5672:5672"
  jetlinsk-gateway:
    image: jetlinks/device-gateway-service
    container_name: device-gateway-service
    ports:
      - "1883:1883"
    environment:
      JAVA_OPTS: -Xms4G -Xmx4G -XX:+UseG1GC
      server.port: 9012
      spring.profiles.active: dev,docker
      test.initDeviceNumber: 10000
    links:
      - redis:redis
      - nacos:nacos-server
      - rabbitmq:rabbitmq
    depends_on:
      - redis
      - nacos
#  log-service:
#    image: jetlinks/log-service
#    container_name: log-service
#    environment:
#      JAVA_OPTS: -Xms2G -Xmx2G -XX:+UseG1GC
#      spring.profiles.active: dev,docker
#    links:
#      - redis:redis
#      - nacos:nacos-server
#      - rabbitmq:rabbitmq
#      - influxdb:influxdb
#      - elasticsearch:elasticsearch
#    depends_on:
#      - redis
#      - nacos
#      - influxdb
#  rule-engine-service:
#    image: jetlinks/rule-engine-service
#    container_name: rule-engine-service
#    environment:
#      spring.profiles.active: dev,docker
#    links:
#      - redis:redis
#      - nacos:nacos-server
#      - rabbitmq:rabbitmq
#      - influxdb:influxdb
#    depends_on:
#      - redis
#      - nacos
#      - influxdb
#  dashbord-gateway:
#    image: jetlinks/dashboard-gateway-service
#    container_name: dashboard-gateway-service
#    ports:
#      - "8000:8000"
#    environment:
#      spring.profiles.active: dev,docker
#    links:
#      - nacos:nacos-server
#      - jetlinsk-gateway:jetlinsk-gateway
#      - log-service:log-service
#      - rule-engine-service:rule-engine-service
#    depends_on:
#      - nacos