version: '2'
services:
  nacos:    # nacos 配置中心以及服务发现
    image: nacos/nacos-server:1.0.0
    container_name: jetlinks-all-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./nacos.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
  redis:
    image: redis:5.0.4
    container_name: jetlinks-all-redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    command: redis-server --appendonly yes
  jetlinsk-gateway:
    image: jetlinks/device-gateway-service
    container_name: device-gateway-service
    ports:
      - "9012:9012"
      - "1883:1883"
    environment:
      server.port: 9012
      spring.profiles.active: dev,docker
    links:
      - redis:redis
      - nacos:nacos-server
    depends_on:
      - redis